### ISSUE TITLE
Fails with packages legitimately containing slashes

### ISSUE THREAD

**Issue by peterhoeg** [rvl/bower2nix#13]
Later versions of https://github.com/sensu/uchiwa use ```angular-tools/ng-jsoneditor``` and while ```bower2nix``` will process ```bower.json```, nix will subsequently fail with:

```
error: invalid character ‘/’ in name ‘angular-tools/ng-jsoneditor-ea138469f157d8f2b54ec5b8dcf4b08a55b61459
```

bower-packages.json:
```
(fetchbower "angular-tools/ng-jsoneditor" "ea138469f157d8f2b54ec5b8dcf4b08a55b61459" "ea138469f157d8f2b54ec5b8dcf4b08a55b61459" "1rr7xf3a2l15g2nmd9svq8ijy1v0igc5jdpwp21kna1kzc65jg3m")
```

Related to #7?

**Comment by rvl** [comment]
Hi, thanks for the report. I was kind of hoping all the web developers would stop using bower... but

Please try applying this fix to nixpkgs: https://github.com/rvl/nixpkgs/commit/efaec90f603762d10d658e80bbe9870badd51e76

It seems to work for me with `uchiwa-web/bower.json`.

**Comment by peterhoeg** [comment]
The mentioned patch partially fixes ```fetchbower```, but when trying to now package the application bower errors out as follows:

```
bower                                      ENOTFOUND Package angular-tools/ng-jsoneditor=angular-tools/ng-jsoneditor not found
```

**Comment by rvl** [comment]
I'm not sure what could be the problem there because uchiwa works for me. See https://gist.github.com/rvl/5012b46b462140fd9d7e4ff940ab0682 . If you download that gist, does it build? The bower.json in there is from current master of uchiwa.

**Comment by peterhoeg** [comment]
Indeed it does - thanks! Are you planning on merging https://github.com/rvl/nixpkgs/commit/efaec90f603762d10d658e80bbe9870badd51e76 ?

**Comment by rvl** [comment]
Great, yes I've just added PR NixOS/nixpkgs#27775.

**Comment by peterhoeg** [comment]
And I just merged it, thanks again!
