### ISSUE TITLE
No release for 3.3.0 as it hasn't been tagged

### ISSUE THREAD

**Issue by peterhoeg** [rvl/bower2nix#14]
Latest available release which is also what we have in nixpkgs is 3.1.1 while 3.3 exists upstream.

**Comment by rvl** [comment]
Hi @peterhoeg, thanks for reminding me -- I have forgotten all about it. I will prepare a release for 17.09 tomorrow.

**Comment by peterhoeg** [comment]
Excellent, thanks. I hit an odd case where wrong hashes were being generated, so I'm really curious to see if that has been fixed in 3.3

**Comment by rvl** [comment]
Release v3.2.0 is here
https://github.com/rvl/bower2nix/releases/tag/v3.2.0

v3.3.0 will be the next version.
