### ISSUE TITLE
Does not work on Node 12

### ISSUE THREAD

**Issue by dasJ** [rvl/bower2nix#20]
I don't really know a lot about nodejs but the error seems to be because of an old fs-extra version.
Full message:
```
$ bower2nix
# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
Parsing /path/to/src/bower.json failed: ReferenceError: primordials is not defined
```

**Comment by superboum** [comment]
This error is due to the dependency `bower-json`. I fixed the error by switching `bower-json` to version `0.8.4` in the `package.json` file.
